#!/usr/bin/env python
'''
# =============================================================================
#      FileName: pSCNAClonal
#        Author: Chu Yanshuo
#         Email: chu@yanshuo.name
#      HomePage: http://yanshuo.name
#       Version: 0.0.1
#    LastChange: 2017-07-14 14:38:12
#       History: Author : Andrew Roth
# =============================================================================
'''
import argparse
from pSCNAClonal.PSSP.run import run_dp_model
from pSCNAClonal.preprocess.run_preprocess import run_preprocess_pSCNAClonal

parser = argparse.ArgumentParser(prog='PSSP')
parser.add_argument('--version', action='version', version='PSSP-0.0.0')
subparsers = parser.add_subparsers()

# -------------------------------------------------------------------------
analyse_parser = subparsers.add_parser(
    'analyse', help='''Start a new PSSP analysis.''')
analyse_parser.add_argument(
    'inputFilePath',
    help='Path to tab separated input file. See examples for format.')
analyse_parser.add_argument(
    'out_dir',
    help='Path where trace file for MCMC sampler will be written.')
analyse_parser.add_argument(
    '--num_iters', default=10000, type=int,
    help='''How many iterations of the MCMC chain will run. Default 10,000.''')
analyse_parser.add_argument(
    '--concentration', default=None, type=int,
    help='''Concentration (alpha) value for DP sampler. If not set it will be
    estimated. Default estimated.''')
analyse_parser.add_argument(
    '--concentration_prior_shape', default=1, type=float,
    help='''Prior on the shape parameter in the prior for the concentration
    parameter. Default 1.''')
analyse_parser.add_argument(
    '--concentration_prior_rate', default=1, type=float,
    help='''Prior on the rate parameter in the prior for the concentration
    parameter. Default 1.''')
analyse_parser.set_defaults(func=run_dp_model)
args = parser.parse_args()
args.func(args)
# ==============================================================================
# Add pSCNAClonal type
# ==============================================================================

parser_pSCNAClonal = subparsers.add_parser('pSCNAClonal',
                                        help='''Out put pSCNAClonal format''')

parser_pSCNAClonal.add_argument('normal_bam',
                             help='''BAM file for normal sample.''')

parser_pSCNAClonal.add_argument('tumor_bam',
                             help='''BAM file for tumor sample.''')

parser_pSCNAClonal.add_argument('reference_genome',
                             help='''FASTA file for reference genome.''')

parser_pSCNAClonal.add_argument('input_filename_base',
                             help='''Base name of the preprocessed input
                             file to be created.''')

parser_pSCNAClonal.add_argument('segments_bed',
                             help='''BED file for segments.''')

parser_pSCNAClonal.add_argument(
    'BICseq_bed_corrected',
    help='''The name of corrected BICseq result file''')

parser_pSCNAClonal.add_argument('--pkl_path',
                             help='''Load the pkl path''')

parser_pSCNAClonal.add_argument('--max_copynumber', default=6, type=int,
                             help='''Set the maximum copy number''')

parser_pSCNAClonal.add_argument('--subclone_num', default=2, type=int,
                             help='''Set the subclone number''')

parser_pSCNAClonal.add_argument('--baseline_thred_LOH', default=0.16, type=float,
                             help='''The threshold of LOH sites fraction
                              within each segment to
                              define the segment is LOH, the range is
                             [baseline_thred_LOH, 1]. Default is
                              0.16.''')

parser_pSCNAClonal.add_argument('--baseline_thred_APM',
                             default=0.2, type=float,
                             help='''The threshold of average P and M SNP sites
                              fraction within each segment to
                              define the segment as baseline, the range is
                             [baseline_thred_APM, 1]. Default is
                              0.2.''')

parser_pSCNAClonal.add_argument('--pkl_flag', default=False, type=bool,
                             help='''The pkl flag''')

parser_pSCNAClonal.add_argument('--min_depth', default=20, type=int,
                             help='''Minimum reads depth required for both
                             normal and tumor samples.  Default is 20.''')

parser_pSCNAClonal.add_argument('--min_base_qual', default=10, type=int,
                             help='''Minimum base quality required.
                             Default is 10.''')

parser_pSCNAClonal.add_argument('--min_map_qual', default=10, type=int,
                             help='''Minimum mapping quality required.
                             Default is 10.''')

parser_pSCNAClonal.add_argument('--process_num', default=1, type=int,
                             help='''Number of processes to launch for
                             preprocessing. Default is 1.''')

parser_pSCNAClonal.add_argument('--gc_correction_method', default="auto",
                             help='''The gc correction method, one of auto and
                             visual''')

parser_pSCNAClonal.set_defaults(func=run_preprocess_pSCNAClonal)
