#!/usr/bin/env python
'''
# =============================================================================
#      FileName: PSSP
#        Author: Chu Yanshuo
#         Email: chu@yanshuo.name
#      HomePage: http://yanshuo.name
#       Version: 0.0.1
#    LastChange: 2017-04-10 16:50:28
#       History: Author : Andrew Roth
# =============================================================================
'''
import argparse
from PSSP.run import run_dp_model

parser = argparse.ArgumentParser(prog='PSSP')
parser.add_argument('--version', action='version', version='PSSP-0.0.0')
subparsers = parser.add_subparsers()

# -------------------------------------------------------------------------
analyse_parser = subparsers.add_parser(
    'analyse', help='''Start a new PSSP analysis.''')
analyse_parser.add_argument(
    'inputFilePsth',
    help='Path to tab separated input file. See examples for format.')
analyse_parser.add_argument(
    'out_dir',
     help='Path where trace file for MCMC sampler will be written.')
analyse_parser.add_argument(
    '--num_iters', default=10000, type=int,
    help='''How many iterations of the MCMC chain will run. Default 10,000.''')
analyse_parser.add_argument(
    '--concentration', default=None, type=int,
    help='''Concentration (alpha) value for DP sampler. If not set it will be
    estimated. Default estimated.''')
analyse_parser.add_argument(
    '--concentration_prior_shape', default=1, type=float,
    help='''Prior on the shape parameter in the prior for the concentration
    parameter. Default 1.''')
analyse_parser.add_argument(
    '--concentration_prior_rate', default=1, type=float,
    help='''Prior on the rate parameter in the prior for the concentration
    parameter. Default 1.''')
analyse_parser.set_defaults(func=run_dp_model)
args = parser.parse_args()
args.func(args)
